/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as BookingStatusRouteImport } from './routes/booking-status'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CustomTourRouteImport } from './routes/custom-tour'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as QrPaymentRouteImport } from './routes/qr-payment'
import { Route as RateCardsRouteImport } from './routes/rate-cards'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as BookingConfirmationBookingNumberRouteImport } from './routes/booking-confirmation.$bookingNumber'
import { Route as CustomerAccountRouteImport } from './routes/customer.account'
import { Route as CustomerLoginRouteImport } from './routes/customer.login'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as FleetIndexRouteImport } from './routes/fleet.index'
import { Route as FleetSlugRouteImport } from './routes/fleet.$slug'
import { Route as HotelsIndexRouteImport } from './routes/hotels.index'
import { Route as HotelsSearchRouteImport } from './routes/hotels.search'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as TourPackagesIndexRouteImport } from './routes/tour-packages.index'
import { Route as TourPackagesSlugRouteImport } from './routes/tour-packages.$slug'
import { Route as BookHotelIndexRouteImport } from './routes/book.hotel.index'
import { Route as BookHotelConfirmationRouteImport } from './routes/book.hotel.confirmation'
import { Route as BookTourPackageIndexRouteImport } from './routes/book.tour-package.index'
import { Route as BookTourPackageConfirmationRouteImport } from './routes/book.tour-package.confirmation'
import { Route as CustomerDashboardIndexRouteImport } from './routes/customer.dashboard.index'
import { Route as CustomerDashboardCancellationsRouteImport } from './routes/customer.dashboard.cancellations'
import { Route as CustomerDashboardConfirmationsRouteImport } from './routes/customer.dashboard.confirmations'
import { Route as CustomerDashboardInvoicesRouteImport } from './routes/customer.dashboard.invoices'
import { Route as CustomerDashboardPaymentsRouteImport } from './routes/customer.dashboard.payments'
import { Route as CustomerDashboardProfileRouteImport } from './routes/customer.dashboard.profile'
import { Route as CustomerDashboardStatusRouteImport } from './routes/customer.dashboard.status'
import { Route as CustomerDashboardSupportRouteImport } from './routes/customer.dashboard.support'
import { Route as CustomerDashboardTravellersRouteImport } from './routes/customer.dashboard.travellers'
import { Route as HotelsDestinationSlugIndexRouteImport } from './routes/hotels.$destinationSlug.index'
import { Route as CustomerDashboardBookingsIndexRouteImport } from './routes/customer.dashboard.bookings.index'
import { Route as CustomerDashboardBookingsHotelRouteImport } from './routes/customer.dashboard.bookings.hotel'
import { Route as CustomerDashboardBookingsTourRouteImport } from './routes/customer.dashboard.bookings.tour'
import { Route as CustomerDashboardBookingsVehicleRouteImport } from './routes/customer.dashboard.bookings.vehicle'
import { Route as HotelsDestinationSlugHotelSlugIndexRouteImport } from './routes/hotels.$destinationSlug.$hotelSlug.index'
import { Route as HotelsDestinationSlugHotelSlugRoomSlugRouteImport } from './routes/hotels.$destinationSlug.$hotelSlug.$roomSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingStatusRoute = BookingStatusRouteImport.update({
  id: '/booking-status',
  path: '/booking-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomTourRoute = CustomTourRouteImport.update({
  id: '/custom-tour',
  path: '/custom-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const QrPaymentRoute = QrPaymentRouteImport.update({
  id: '/qr-payment',
  path: '/qr-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const RateCardsRoute = RateCardsRouteImport.update({
  id: '/rate-cards',
  path: '/rate-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationBookingNumberRoute =
  BookingConfirmationBookingNumberRouteImport.update({
    id: '/booking-confirmation/$bookingNumber',
    path: '/booking-confirmation/$bookingNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerAccountRoute = CustomerAccountRouteImport.update({
  id: '/customer/account',
  path: '/customer/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer/login',
  path: '/customer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetIndexRoute = FleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetSlugRoute = FleetSlugRouteImport.update({
  id: '/fleet/$slug',
  path: '/fleet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsSearchRoute = HotelsSearchRouteImport.update({
  id: '/hotels/search',
  path: '/hotels/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TourPackagesIndexRoute = TourPackagesIndexRouteImport.update({
  id: '/tour-packages/',
  path: '/tour-packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourPackagesSlugRoute = TourPackagesSlugRouteImport.update({
  id: '/tour-packages/$slug',
  path: '/tour-packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookHotelIndexRoute = BookHotelIndexRouteImport.update({
  id: '/book/hotel/',
  path: '/book/hotel/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookHotelConfirmationRoute = BookHotelConfirmationRouteImport.update({
  id: '/book/hotel/confirmation',
  path: '/book/hotel/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTourPackageIndexRoute = BookTourPackageIndexRouteImport.update({
  id: '/book/tour-package/',
  path: '/book/tour-package/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTourPackageConfirmationRoute =
  BookTourPackageConfirmationRouteImport.update({
    id: '/book/tour-package/confirmation',
    path: '/book/tour-package/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardIndexRoute = CustomerDashboardIndexRouteImport.update({
  id: '/customer/dashboard/',
  path: '/customer/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardCancellationsRoute =
  CustomerDashboardCancellationsRouteImport.update({
    id: '/customer/dashboard/cancellations',
    path: '/customer/dashboard/cancellations',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardConfirmationsRoute =
  CustomerDashboardConfirmationsRouteImport.update({
    id: '/customer/dashboard/confirmations',
    path: '/customer/dashboard/confirmations',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardInvoicesRoute =
  CustomerDashboardInvoicesRouteImport.update({
    id: '/customer/dashboard/invoices',
    path: '/customer/dashboard/invoices',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardPaymentsRoute =
  CustomerDashboardPaymentsRouteImport.update({
    id: '/customer/dashboard/payments',
    path: '/customer/dashboard/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardProfileRoute =
  CustomerDashboardProfileRouteImport.update({
    id: '/customer/dashboard/profile',
    path: '/customer/dashboard/profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardStatusRoute = CustomerDashboardStatusRouteImport.update({
  id: '/customer/dashboard/status',
  path: '/customer/dashboard/status',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardSupportRoute =
  CustomerDashboardSupportRouteImport.update({
    id: '/customer/dashboard/support',
    path: '/customer/dashboard/support',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardTravellersRoute =
  CustomerDashboardTravellersRouteImport.update({
    id: '/customer/dashboard/travellers',
    path: '/customer/dashboard/travellers',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelsDestinationSlugIndexRoute =
  HotelsDestinationSlugIndexRouteImport.update({
    id: '/hotels/$destinationSlug/',
    path: '/hotels/$destinationSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardBookingsIndexRoute =
  CustomerDashboardBookingsIndexRouteImport.update({
    id: '/customer/dashboard/bookings/',
    path: '/customer/dashboard/bookings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardBookingsHotelRoute =
  CustomerDashboardBookingsHotelRouteImport.update({
    id: '/customer/dashboard/bookings/hotel',
    path: '/customer/dashboard/bookings/hotel',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardBookingsTourRoute =
  CustomerDashboardBookingsTourRouteImport.update({
    id: '/customer/dashboard/bookings/tour',
    path: '/customer/dashboard/bookings/tour',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardBookingsVehicleRoute =
  CustomerDashboardBookingsVehicleRouteImport.update({
    id: '/customer/dashboard/bookings/vehicle',
    path: '/customer/dashboard/bookings/vehicle',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelsDestinationSlugHotelSlugIndexRoute =
  HotelsDestinationSlugHotelSlugIndexRouteImport.update({
    id: '/hotels/$destinationSlug/$hotelSlug/',
    path: '/hotels/$destinationSlug/$hotelSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelsDestinationSlugHotelSlugRoomSlugRoute =
  HotelsDestinationSlugHotelSlugRoomSlugRouteImport.update({
    id: '/hotels/$destinationSlug/$hotelSlug/$roomSlug',
    path: '/hotels/$destinationSlug/$hotelSlug/$roomSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/booking-status': typeof BookingStatusRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/custom-tour': typeof CustomTourRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/qr-payment': typeof QrPaymentRoute
  '/rate-cards': typeof RateCardsRoute
  '/testimonials': typeof TestimonialsRoute
  '/booking-confirmation/$bookingNumber': typeof BookingConfirmationBookingNumberRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/login': typeof CustomerLoginRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/fleet/$slug': typeof FleetSlugRoute
  '/hotels/search': typeof HotelsSearchRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tour-packages/$slug': typeof TourPackagesSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/fleet/': typeof FleetIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tour-packages/': typeof TourPackagesIndexRoute
  '/book/hotel/confirmation': typeof BookHotelConfirmationRoute
  '/book/tour-package/confirmation': typeof BookTourPackageConfirmationRoute
  '/customer/dashboard/cancellations': typeof CustomerDashboardCancellationsRoute
  '/customer/dashboard/confirmations': typeof CustomerDashboardConfirmationsRoute
  '/customer/dashboard/invoices': typeof CustomerDashboardInvoicesRoute
  '/customer/dashboard/payments': typeof CustomerDashboardPaymentsRoute
  '/customer/dashboard/profile': typeof CustomerDashboardProfileRoute
  '/customer/dashboard/status': typeof CustomerDashboardStatusRoute
  '/customer/dashboard/support': typeof CustomerDashboardSupportRoute
  '/customer/dashboard/travellers': typeof CustomerDashboardTravellersRoute
  '/book/hotel/': typeof BookHotelIndexRoute
  '/book/tour-package/': typeof BookTourPackageIndexRoute
  '/customer/dashboard/': typeof CustomerDashboardIndexRoute
  '/hotels/$destinationSlug/': typeof HotelsDestinationSlugIndexRoute
  '/customer/dashboard/bookings/hotel': typeof CustomerDashboardBookingsHotelRoute
  '/customer/dashboard/bookings/tour': typeof CustomerDashboardBookingsTourRoute
  '/customer/dashboard/bookings/vehicle': typeof CustomerDashboardBookingsVehicleRoute
  '/hotels/$destinationSlug/$hotelSlug/$roomSlug': typeof HotelsDestinationSlugHotelSlugRoomSlugRoute
  '/customer/dashboard/bookings/': typeof CustomerDashboardBookingsIndexRoute
  '/hotels/$destinationSlug/$hotelSlug/': typeof HotelsDestinationSlugHotelSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/booking-status': typeof BookingStatusRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/custom-tour': typeof CustomTourRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/qr-payment': typeof QrPaymentRoute
  '/rate-cards': typeof RateCardsRoute
  '/testimonials': typeof TestimonialsRoute
  '/booking-confirmation/$bookingNumber': typeof BookingConfirmationBookingNumberRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/login': typeof CustomerLoginRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/fleet/$slug': typeof FleetSlugRoute
  '/hotels/search': typeof HotelsSearchRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tour-packages/$slug': typeof TourPackagesSlugRoute
  '/destinations': typeof DestinationsIndexRoute
  '/fleet': typeof FleetIndexRoute
  '/hotels': typeof HotelsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/tour-packages': typeof TourPackagesIndexRoute
  '/book/hotel/confirmation': typeof BookHotelConfirmationRoute
  '/book/tour-package/confirmation': typeof BookTourPackageConfirmationRoute
  '/customer/dashboard/cancellations': typeof CustomerDashboardCancellationsRoute
  '/customer/dashboard/confirmations': typeof CustomerDashboardConfirmationsRoute
  '/customer/dashboard/invoices': typeof CustomerDashboardInvoicesRoute
  '/customer/dashboard/payments': typeof CustomerDashboardPaymentsRoute
  '/customer/dashboard/profile': typeof CustomerDashboardProfileRoute
  '/customer/dashboard/status': typeof CustomerDashboardStatusRoute
  '/customer/dashboard/support': typeof CustomerDashboardSupportRoute
  '/customer/dashboard/travellers': typeof CustomerDashboardTravellersRoute
  '/book/hotel': typeof BookHotelIndexRoute
  '/book/tour-package': typeof BookTourPackageIndexRoute
  '/customer/dashboard': typeof CustomerDashboardIndexRoute
  '/hotels/$destinationSlug': typeof HotelsDestinationSlugIndexRoute
  '/customer/dashboard/bookings/hotel': typeof CustomerDashboardBookingsHotelRoute
  '/customer/dashboard/bookings/tour': typeof CustomerDashboardBookingsTourRoute
  '/customer/dashboard/bookings/vehicle': typeof CustomerDashboardBookingsVehicleRoute
  '/hotels/$destinationSlug/$hotelSlug/$roomSlug': typeof HotelsDestinationSlugHotelSlugRoomSlugRoute
  '/customer/dashboard/bookings': typeof CustomerDashboardBookingsIndexRoute
  '/hotels/$destinationSlug/$hotelSlug': typeof HotelsDestinationSlugHotelSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/booking-status': typeof BookingStatusRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/custom-tour': typeof CustomTourRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/qr-payment': typeof QrPaymentRoute
  '/rate-cards': typeof RateCardsRoute
  '/testimonials': typeof TestimonialsRoute
  '/booking-confirmation/$bookingNumber': typeof BookingConfirmationBookingNumberRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/login': typeof CustomerLoginRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/fleet/$slug': typeof FleetSlugRoute
  '/hotels/search': typeof HotelsSearchRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tour-packages/$slug': typeof TourPackagesSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/fleet/': typeof FleetIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tour-packages/': typeof TourPackagesIndexRoute
  '/book/hotel/confirmation': typeof BookHotelConfirmationRoute
  '/book/tour-package/confirmation': typeof BookTourPackageConfirmationRoute
  '/customer/dashboard/cancellations': typeof CustomerDashboardCancellationsRoute
  '/customer/dashboard/confirmations': typeof CustomerDashboardConfirmationsRoute
  '/customer/dashboard/invoices': typeof CustomerDashboardInvoicesRoute
  '/customer/dashboard/payments': typeof CustomerDashboardPaymentsRoute
  '/customer/dashboard/profile': typeof CustomerDashboardProfileRoute
  '/customer/dashboard/status': typeof CustomerDashboardStatusRoute
  '/customer/dashboard/support': typeof CustomerDashboardSupportRoute
  '/customer/dashboard/travellers': typeof CustomerDashboardTravellersRoute
  '/book/hotel/': typeof BookHotelIndexRoute
  '/book/tour-package/': typeof BookTourPackageIndexRoute
  '/customer/dashboard/': typeof CustomerDashboardIndexRoute
  '/hotels/$destinationSlug/': typeof HotelsDestinationSlugIndexRoute
  '/customer/dashboard/bookings/hotel': typeof CustomerDashboardBookingsHotelRoute
  '/customer/dashboard/bookings/tour': typeof CustomerDashboardBookingsTourRoute
  '/customer/dashboard/bookings/vehicle': typeof CustomerDashboardBookingsVehicleRoute
  '/hotels/$destinationSlug/$hotelSlug/$roomSlug': typeof HotelsDestinationSlugHotelSlugRoomSlugRoute
  '/customer/dashboard/bookings/': typeof CustomerDashboardBookingsIndexRoute
  '/hotels/$destinationSlug/$hotelSlug/': typeof HotelsDestinationSlugHotelSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-us'
    | '/booking-status'
    | '/contact'
    | '/contact-us'
    | '/custom-tour'
    | '/faqs'
    | '/gallery'
    | '/packages'
    | '/qr-payment'
    | '/rate-cards'
    | '/testimonials'
    | '/booking-confirmation/$bookingNumber'
    | '/customer/account'
    | '/customer/login'
    | '/destinations/$slug'
    | '/fleet/$slug'
    | '/hotels/search'
    | '/services/$slug'
    | '/tour-packages/$slug'
    | '/destinations/'
    | '/fleet/'
    | '/hotels/'
    | '/services/'
    | '/tour-packages/'
    | '/book/hotel/confirmation'
    | '/book/tour-package/confirmation'
    | '/customer/dashboard/cancellations'
    | '/customer/dashboard/confirmations'
    | '/customer/dashboard/invoices'
    | '/customer/dashboard/payments'
    | '/customer/dashboard/profile'
    | '/customer/dashboard/status'
    | '/customer/dashboard/support'
    | '/customer/dashboard/travellers'
    | '/book/hotel/'
    | '/book/tour-package/'
    | '/customer/dashboard/'
    | '/hotels/$destinationSlug/'
    | '/customer/dashboard/bookings/hotel'
    | '/customer/dashboard/bookings/tour'
    | '/customer/dashboard/bookings/vehicle'
    | '/hotels/$destinationSlug/$hotelSlug/$roomSlug'
    | '/customer/dashboard/bookings/'
    | '/hotels/$destinationSlug/$hotelSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-us'
    | '/booking-status'
    | '/contact'
    | '/contact-us'
    | '/custom-tour'
    | '/faqs'
    | '/gallery'
    | '/packages'
    | '/qr-payment'
    | '/rate-cards'
    | '/testimonials'
    | '/booking-confirmation/$bookingNumber'
    | '/customer/account'
    | '/customer/login'
    | '/destinations/$slug'
    | '/fleet/$slug'
    | '/hotels/search'
    | '/services/$slug'
    | '/tour-packages/$slug'
    | '/destinations'
    | '/fleet'
    | '/hotels'
    | '/services'
    | '/tour-packages'
    | '/book/hotel/confirmation'
    | '/book/tour-package/confirmation'
    | '/customer/dashboard/cancellations'
    | '/customer/dashboard/confirmations'
    | '/customer/dashboard/invoices'
    | '/customer/dashboard/payments'
    | '/customer/dashboard/profile'
    | '/customer/dashboard/status'
    | '/customer/dashboard/support'
    | '/customer/dashboard/travellers'
    | '/book/hotel'
    | '/book/tour-package'
    | '/customer/dashboard'
    | '/hotels/$destinationSlug'
    | '/customer/dashboard/bookings/hotel'
    | '/customer/dashboard/bookings/tour'
    | '/customer/dashboard/bookings/vehicle'
    | '/hotels/$destinationSlug/$hotelSlug/$roomSlug'
    | '/customer/dashboard/bookings'
    | '/hotels/$destinationSlug/$hotelSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-us'
    | '/booking-status'
    | '/contact'
    | '/contact-us'
    | '/custom-tour'
    | '/faqs'
    | '/gallery'
    | '/packages'
    | '/qr-payment'
    | '/rate-cards'
    | '/testimonials'
    | '/booking-confirmation/$bookingNumber'
    | '/customer/account'
    | '/customer/login'
    | '/destinations/$slug'
    | '/fleet/$slug'
    | '/hotels/search'
    | '/services/$slug'
    | '/tour-packages/$slug'
    | '/destinations/'
    | '/fleet/'
    | '/hotels/'
    | '/services/'
    | '/tour-packages/'
    | '/book/hotel/confirmation'
    | '/book/tour-package/confirmation'
    | '/customer/dashboard/cancellations'
    | '/customer/dashboard/confirmations'
    | '/customer/dashboard/invoices'
    | '/customer/dashboard/payments'
    | '/customer/dashboard/profile'
    | '/customer/dashboard/status'
    | '/customer/dashboard/support'
    | '/customer/dashboard/travellers'
    | '/book/hotel/'
    | '/book/tour-package/'
    | '/customer/dashboard/'
    | '/hotels/$destinationSlug/'
    | '/customer/dashboard/bookings/hotel'
    | '/customer/dashboard/bookings/tour'
    | '/customer/dashboard/bookings/vehicle'
    | '/hotels/$destinationSlug/$hotelSlug/$roomSlug'
    | '/customer/dashboard/bookings/'
    | '/hotels/$destinationSlug/$hotelSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutUsRoute: typeof AboutUsRoute
  BookingStatusRoute: typeof BookingStatusRoute
  ContactRoute: typeof ContactRoute
  ContactUsRoute: typeof ContactUsRoute
  CustomTourRoute: typeof CustomTourRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  PackagesRoute: typeof PackagesRoute
  QrPaymentRoute: typeof QrPaymentRoute
  RateCardsRoute: typeof RateCardsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  BookingConfirmationBookingNumberRoute: typeof BookingConfirmationBookingNumberRoute
  CustomerAccountRoute: typeof CustomerAccountRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  FleetSlugRoute: typeof FleetSlugRoute
  HotelsSearchRoute: typeof HotelsSearchRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  TourPackagesSlugRoute: typeof TourPackagesSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  FleetIndexRoute: typeof FleetIndexRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TourPackagesIndexRoute: typeof TourPackagesIndexRoute
  BookHotelConfirmationRoute: typeof BookHotelConfirmationRoute
  BookTourPackageConfirmationRoute: typeof BookTourPackageConfirmationRoute
  CustomerDashboardCancellationsRoute: typeof CustomerDashboardCancellationsRoute
  CustomerDashboardConfirmationsRoute: typeof CustomerDashboardConfirmationsRoute
  CustomerDashboardInvoicesRoute: typeof CustomerDashboardInvoicesRoute
  CustomerDashboardPaymentsRoute: typeof CustomerDashboardPaymentsRoute
  CustomerDashboardProfileRoute: typeof CustomerDashboardProfileRoute
  CustomerDashboardStatusRoute: typeof CustomerDashboardStatusRoute
  CustomerDashboardSupportRoute: typeof CustomerDashboardSupportRoute
  CustomerDashboardTravellersRoute: typeof CustomerDashboardTravellersRoute
  BookHotelIndexRoute: typeof BookHotelIndexRoute
  BookTourPackageIndexRoute: typeof BookTourPackageIndexRoute
  CustomerDashboardIndexRoute: typeof CustomerDashboardIndexRoute
  HotelsDestinationSlugIndexRoute: typeof HotelsDestinationSlugIndexRoute
  CustomerDashboardBookingsHotelRoute: typeof CustomerDashboardBookingsHotelRoute
  CustomerDashboardBookingsTourRoute: typeof CustomerDashboardBookingsTourRoute
  CustomerDashboardBookingsVehicleRoute: typeof CustomerDashboardBookingsVehicleRoute
  HotelsDestinationSlugHotelSlugRoomSlugRoute: typeof HotelsDestinationSlugHotelSlugRoomSlugRoute
  CustomerDashboardBookingsIndexRoute: typeof CustomerDashboardBookingsIndexRoute
  HotelsDestinationSlugHotelSlugIndexRoute: typeof HotelsDestinationSlugHotelSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-status': {
      id: '/booking-status'
      path: '/booking-status'
      fullPath: '/booking-status'
      preLoaderRoute: typeof BookingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-tour': {
      id: '/custom-tour'
      path: '/custom-tour'
      fullPath: '/custom-tour'
      preLoaderRoute: typeof CustomTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-payment': {
      id: '/qr-payment'
      path: '/qr-payment'
      fullPath: '/qr-payment'
      preLoaderRoute: typeof QrPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-cards': {
      id: '/rate-cards'
      path: '/rate-cards'
      fullPath: '/rate-cards'
      preLoaderRoute: typeof RateCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmation/$bookingNumber': {
      id: '/booking-confirmation/$bookingNumber'
      path: '/booking-confirmation/$bookingNumber'
      fullPath: '/booking-confirmation/$bookingNumber'
      preLoaderRoute: typeof BookingConfirmationBookingNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/account': {
      id: '/customer/account'
      path: '/customer/account'
      fullPath: '/customer/account'
      preLoaderRoute: typeof CustomerAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/customer/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/': {
      id: '/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof FleetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/$slug': {
      id: '/fleet/$slug'
      path: '/fleet/$slug'
      fullPath: '/fleet/$slug'
      preLoaderRoute: typeof FleetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/search': {
      id: '/hotels/search'
      path: '/hotels/search'
      fullPath: '/hotels/search'
      preLoaderRoute: typeof HotelsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-packages/': {
      id: '/tour-packages/'
      path: '/tour-packages'
      fullPath: '/tour-packages/'
      preLoaderRoute: typeof TourPackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-packages/$slug': {
      id: '/tour-packages/$slug'
      path: '/tour-packages/$slug'
      fullPath: '/tour-packages/$slug'
      preLoaderRoute: typeof TourPackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/hotel/': {
      id: '/book/hotel/'
      path: '/book/hotel'
      fullPath: '/book/hotel/'
      preLoaderRoute: typeof BookHotelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/hotel/confirmation': {
      id: '/book/hotel/confirmation'
      path: '/book/hotel/confirmation'
      fullPath: '/book/hotel/confirmation'
      preLoaderRoute: typeof BookHotelConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/tour-package/': {
      id: '/book/tour-package/'
      path: '/book/tour-package'
      fullPath: '/book/tour-package/'
      preLoaderRoute: typeof BookTourPackageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/tour-package/confirmation': {
      id: '/book/tour-package/confirmation'
      path: '/book/tour-package/confirmation'
      fullPath: '/book/tour-package/confirmation'
      preLoaderRoute: typeof BookTourPackageConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/': {
      id: '/customer/dashboard/'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard/'
      preLoaderRoute: typeof CustomerDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/cancellations': {
      id: '/customer/dashboard/cancellations'
      path: '/customer/dashboard/cancellations'
      fullPath: '/customer/dashboard/cancellations'
      preLoaderRoute: typeof CustomerDashboardCancellationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/confirmations': {
      id: '/customer/dashboard/confirmations'
      path: '/customer/dashboard/confirmations'
      fullPath: '/customer/dashboard/confirmations'
      preLoaderRoute: typeof CustomerDashboardConfirmationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/invoices': {
      id: '/customer/dashboard/invoices'
      path: '/customer/dashboard/invoices'
      fullPath: '/customer/dashboard/invoices'
      preLoaderRoute: typeof CustomerDashboardInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/payments': {
      id: '/customer/dashboard/payments'
      path: '/customer/dashboard/payments'
      fullPath: '/customer/dashboard/payments'
      preLoaderRoute: typeof CustomerDashboardPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/profile': {
      id: '/customer/dashboard/profile'
      path: '/customer/dashboard/profile'
      fullPath: '/customer/dashboard/profile'
      preLoaderRoute: typeof CustomerDashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/status': {
      id: '/customer/dashboard/status'
      path: '/customer/dashboard/status'
      fullPath: '/customer/dashboard/status'
      preLoaderRoute: typeof CustomerDashboardStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/support': {
      id: '/customer/dashboard/support'
      path: '/customer/dashboard/support'
      fullPath: '/customer/dashboard/support'
      preLoaderRoute: typeof CustomerDashboardSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/travellers': {
      id: '/customer/dashboard/travellers'
      path: '/customer/dashboard/travellers'
      fullPath: '/customer/dashboard/travellers'
      preLoaderRoute: typeof CustomerDashboardTravellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$destinationSlug/': {
      id: '/hotels/$destinationSlug/'
      path: '/hotels/$destinationSlug'
      fullPath: '/hotels/$destinationSlug/'
      preLoaderRoute: typeof HotelsDestinationSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/bookings/': {
      id: '/customer/dashboard/bookings/'
      path: '/customer/dashboard/bookings'
      fullPath: '/customer/dashboard/bookings/'
      preLoaderRoute: typeof CustomerDashboardBookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/bookings/hotel': {
      id: '/customer/dashboard/bookings/hotel'
      path: '/customer/dashboard/bookings/hotel'
      fullPath: '/customer/dashboard/bookings/hotel'
      preLoaderRoute: typeof CustomerDashboardBookingsHotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/bookings/tour': {
      id: '/customer/dashboard/bookings/tour'
      path: '/customer/dashboard/bookings/tour'
      fullPath: '/customer/dashboard/bookings/tour'
      preLoaderRoute: typeof CustomerDashboardBookingsTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/bookings/vehicle': {
      id: '/customer/dashboard/bookings/vehicle'
      path: '/customer/dashboard/bookings/vehicle'
      fullPath: '/customer/dashboard/bookings/vehicle'
      preLoaderRoute: typeof CustomerDashboardBookingsVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$destinationSlug/$hotelSlug/': {
      id: '/hotels/$destinationSlug/$hotelSlug/'
      path: '/hotels/$destinationSlug/$hotelSlug'
      fullPath: '/hotels/$destinationSlug/$hotelSlug/'
      preLoaderRoute: typeof HotelsDestinationSlugHotelSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$destinationSlug/$hotelSlug/$roomSlug': {
      id: '/hotels/$destinationSlug/$hotelSlug/$roomSlug'
      path: '/hotels/$destinationSlug/$hotelSlug/$roomSlug'
      fullPath: '/hotels/$destinationSlug/$hotelSlug/$roomSlug'
      preLoaderRoute: typeof HotelsDestinationSlugHotelSlugRoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutUsRoute: AboutUsRoute,
  BookingStatusRoute: BookingStatusRoute,
  ContactRoute: ContactRoute,
  ContactUsRoute: ContactUsRoute,
  CustomTourRoute: CustomTourRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  PackagesRoute: PackagesRoute,
  QrPaymentRoute: QrPaymentRoute,
  RateCardsRoute: RateCardsRoute,
  TestimonialsRoute: TestimonialsRoute,
  BookingConfirmationBookingNumberRoute: BookingConfirmationBookingNumberRoute,
  CustomerAccountRoute: CustomerAccountRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  FleetSlugRoute: FleetSlugRoute,
  HotelsSearchRoute: HotelsSearchRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  TourPackagesSlugRoute: TourPackagesSlugRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  FleetIndexRoute: FleetIndexRoute,
  HotelsIndexRoute: HotelsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TourPackagesIndexRoute: TourPackagesIndexRoute,
  BookHotelConfirmationRoute: BookHotelConfirmationRoute,
  BookTourPackageConfirmationRoute: BookTourPackageConfirmationRoute,
  CustomerDashboardCancellationsRoute: CustomerDashboardCancellationsRoute,
  CustomerDashboardConfirmationsRoute: CustomerDashboardConfirmationsRoute,
  CustomerDashboardInvoicesRoute: CustomerDashboardInvoicesRoute,
  CustomerDashboardPaymentsRoute: CustomerDashboardPaymentsRoute,
  CustomerDashboardProfileRoute: CustomerDashboardProfileRoute,
  CustomerDashboardStatusRoute: CustomerDashboardStatusRoute,
  CustomerDashboardSupportRoute: CustomerDashboardSupportRoute,
  CustomerDashboardTravellersRoute: CustomerDashboardTravellersRoute,
  BookHotelIndexRoute: BookHotelIndexRoute,
  BookTourPackageIndexRoute: BookTourPackageIndexRoute,
  CustomerDashboardIndexRoute: CustomerDashboardIndexRoute,
  HotelsDestinationSlugIndexRoute: HotelsDestinationSlugIndexRoute,
  CustomerDashboardBookingsHotelRoute: CustomerDashboardBookingsHotelRoute,
  CustomerDashboardBookingsTourRoute: CustomerDashboardBookingsTourRoute,
  CustomerDashboardBookingsVehicleRoute: CustomerDashboardBookingsVehicleRoute,
  HotelsDestinationSlugHotelSlugRoomSlugRoute:
    HotelsDestinationSlugHotelSlugRoomSlugRoute,
  CustomerDashboardBookingsIndexRoute: CustomerDashboardBookingsIndexRoute,
  HotelsDestinationSlugHotelSlugIndexRoute:
    HotelsDestinationSlugHotelSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
