/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingStatusRouteImport } from './routes/booking-status'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CustomTourRouteImport } from './routes/custom-tour'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as QrPaymentRouteImport } from './routes/qr-payment'
import { Route as RateCardsRouteImport } from './routes/rate-cards'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as BookingConfirmationBookingNumberRouteImport } from './routes/booking-confirmation.$bookingNumber'
import { Route as CustomerAccountRouteImport } from './routes/customer.account'
import { Route as CustomerLoginRouteImport } from './routes/customer.login'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as FleetIndexRouteImport } from './routes/fleet.index'
import { Route as FleetSlugRouteImport } from './routes/fleet.$slug'
import { Route as HotelsIndexRouteImport } from './routes/hotels.index'
import { Route as HotelsSearchRouteImport } from './routes/hotels.search'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as TourPackagesIndexRouteImport } from './routes/tour-packages.index'
import { Route as TourPackagesSlugRouteImport } from './routes/tour-packages.$slug'
import { Route as AdminAdministrationLogsRouteImport } from './routes/admin.administration.logs'
import { Route as AdminAdministrationUsersRouteImport } from './routes/admin.administration.users'
import { Route as AdminCmsIndexRouteImport } from './routes/admin.cms.index'
import { Route as AdminCmsHeroRouteImport } from './routes/admin.cms.hero'
import { Route as AdminCmsTestimonialsRouteImport } from './routes/admin.cms.testimonials'
import { Route as AdminContentFaqsRouteImport } from './routes/admin.content.faqs'
import { Route as AdminContentFooterRouteImport } from './routes/admin.content.footer'
import { Route as AdminContentGalleryRouteImport } from './routes/admin.content.gallery'
import { Route as AdminContentHeroRouteImport } from './routes/admin.content.hero'
import { Route as AdminContentHomepageRouteImport } from './routes/admin.content.homepage'
import { Route as AdminContentNavigationRouteImport } from './routes/admin.content.navigation'
import { Route as AdminContentTestimonialsRouteImport } from './routes/admin.content.testimonials'
import { Route as AdminOperationsBookingsRouteImport } from './routes/admin.operations.bookings'
import { Route as AdminOperationsCustomersRouteImport } from './routes/admin.operations.customers'
import { Route as AdminOperationsDriversRouteImport } from './routes/admin.operations.drivers'
import { Route as AdminOperationsEnquiriesRouteImport } from './routes/admin.operations.enquiries'
import { Route as AdminOperationsPaymentsRouteImport } from './routes/admin.operations.payments'
import { Route as AdminOperationsRoutesRouteImport } from './routes/admin.operations.routes'
import { Route as AdminOperationsVehiclesRouteImport } from './routes/admin.operations.vehicles'
import { Route as AdminProductsDestinationsRouteImport } from './routes/admin.products.destinations'
import { Route as AdminProductsFleetRouteImport } from './routes/admin.products.fleet'
import { Route as AdminProductsHotelsRouteImport } from './routes/admin.products.hotels'
import { Route as AdminProductsPackagesRouteImport } from './routes/admin.products.packages'
import { Route as AdminProductsServicesRouteImport } from './routes/admin.products.services'
import { Route as AdminReportsBookingsRouteImport } from './routes/admin.reports.bookings'
import { Route as AdminReportsRevenueRouteImport } from './routes/admin.reports.revenue'
import { Route as AdminSettingsBookingRouteImport } from './routes/admin.settings.booking'
import { Route as AdminSettingsContactRouteImport } from './routes/admin.settings.contact'
import { Route as AdminSettingsGeneralRouteImport } from './routes/admin.settings.general'
import { Route as AdminSettingsPaymentRouteImport } from './routes/admin.settings.payment'
import { Route as BookHotelIndexRouteImport } from './routes/book.hotel.index'
import { Route as BookHotelConfirmationRouteImport } from './routes/book.hotel.confirmation'
import { Route as BookTourPackageIndexRouteImport } from './routes/book.tour-package.index'
import { Route as BookTourPackageConfirmationRouteImport } from './routes/book.tour-package.confirmation'
import { Route as CustomerDashboardIndexRouteImport } from './routes/customer.dashboard.index'
import { Route as CustomerDashboardCancellationsRouteImport } from './routes/customer.dashboard.cancellations'
import { Route as CustomerDashboardConfirmationsRouteImport } from './routes/customer.dashboard.confirmations'
import { Route as CustomerDashboardInvoicesRouteImport } from './routes/customer.dashboard.invoices'
import { Route as CustomerDashboardPaymentsRouteImport } from './routes/customer.dashboard.payments'
import { Route as CustomerDashboardProfileRouteImport } from './routes/customer.dashboard.profile'
import { Route as CustomerDashboardStatusRouteImport } from './routes/customer.dashboard.status'
import { Route as CustomerDashboardSupportRouteImport } from './routes/customer.dashboard.support'
import { Route as CustomerDashboardTravellersRouteImport } from './routes/customer.dashboard.travellers'
import { Route as HotelsDestinationSlugIndexRouteImport } from './routes/hotels.$destinationSlug.index'
import { Route as CustomerDashboardBookingsIndexRouteImport } from './routes/customer.dashboard.bookings.index'
import { Route as CustomerDashboardBookingsHotelRouteImport } from './routes/customer.dashboard.bookings.hotel'
import { Route as CustomerDashboardBookingsTourRouteImport } from './routes/customer.dashboard.bookings.tour'
import { Route as CustomerDashboardBookingsVehicleRouteImport } from './routes/customer.dashboard.bookings.vehicle'
import { Route as HotelsDestinationSlugHotelSlugIndexRouteImport } from './routes/hotels.$destinationSlug.$hotelSlug.index'
import { Route as HotelsDestinationSlugHotelSlugRoomSlugRouteImport } from './routes/hotels.$destinationSlug.$hotelSlug.$roomSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingStatusRoute = BookingStatusRouteImport.update({
  id: '/booking-status',
  path: '/booking-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomTourRoute = CustomTourRouteImport.update({
  id: '/custom-tour',
  path: '/custom-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const QrPaymentRoute = QrPaymentRouteImport.update({
  id: '/qr-payment',
  path: '/qr-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const RateCardsRoute = RateCardsRouteImport.update({
  id: '/rate-cards',
  path: '/rate-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const BookingConfirmationBookingNumberRoute =
  BookingConfirmationBookingNumberRouteImport.update({
    id: '/booking-confirmation/$bookingNumber',
    path: '/booking-confirmation/$bookingNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerAccountRoute = CustomerAccountRouteImport.update({
  id: '/customer/account',
  path: '/customer/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer/login',
  path: '/customer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetIndexRoute = FleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetSlugRoute = FleetSlugRouteImport.update({
  id: '/fleet/$slug',
  path: '/fleet/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsSearchRoute = HotelsSearchRouteImport.update({
  id: '/hotels/search',
  path: '/hotels/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TourPackagesIndexRoute = TourPackagesIndexRouteImport.update({
  id: '/tour-packages/',
  path: '/tour-packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourPackagesSlugRoute = TourPackagesSlugRouteImport.update({
  id: '/tour-packages/$slug',
  path: '/tour-packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdministrationLogsRoute = AdminAdministrationLogsRouteImport.update({
  id: '/administration/logs',
  path: '/administration/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministrationUsersRoute =
  AdminAdministrationUsersRouteImport.update({
    id: '/administration/users',
    path: '/administration/users',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCmsIndexRoute = AdminCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsHeroRoute = AdminCmsHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsTestimonialsRoute = AdminCmsTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminContentFaqsRoute = AdminContentFaqsRouteImport.update({
  id: '/content/faqs',
  path: '/content/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentFooterRoute = AdminContentFooterRouteImport.update({
  id: '/content/footer',
  path: '/content/footer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentGalleryRoute = AdminContentGalleryRouteImport.update({
  id: '/content/gallery',
  path: '/content/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentHeroRoute = AdminContentHeroRouteImport.update({
  id: '/content/hero',
  path: '/content/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentHomepageRoute = AdminContentHomepageRouteImport.update({
  id: '/content/homepage',
  path: '/content/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentNavigationRoute = AdminContentNavigationRouteImport.update({
  id: '/content/navigation',
  path: '/content/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentTestimonialsRoute =
  AdminContentTestimonialsRouteImport.update({
    id: '/content/testimonials',
    path: '/content/testimonials',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOperationsBookingsRoute = AdminOperationsBookingsRouteImport.update({
  id: '/operations/bookings',
  path: '/operations/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsCustomersRoute =
  AdminOperationsCustomersRouteImport.update({
    id: '/operations/customers',
    path: '/operations/customers',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOperationsDriversRoute = AdminOperationsDriversRouteImport.update({
  id: '/operations/drivers',
  path: '/operations/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsEnquiriesRoute =
  AdminOperationsEnquiriesRouteImport.update({
    id: '/operations/enquiries',
    path: '/operations/enquiries',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOperationsPaymentsRoute = AdminOperationsPaymentsRouteImport.update({
  id: '/operations/payments',
  path: '/operations/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsRoutesRoute = AdminOperationsRoutesRouteImport.update({
  id: '/operations/routes',
  path: '/operations/routes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperationsVehiclesRoute = AdminOperationsVehiclesRouteImport.update({
  id: '/operations/vehicles',
  path: '/operations/vehicles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsDestinationsRoute =
  AdminProductsDestinationsRouteImport.update({
    id: '/products/destinations',
    path: '/products/destinations',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProductsFleetRoute = AdminProductsFleetRouteImport.update({
  id: '/products/fleet',
  path: '/products/fleet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsHotelsRoute = AdminProductsHotelsRouteImport.update({
  id: '/products/hotels',
  path: '/products/hotels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsPackagesRoute = AdminProductsPackagesRouteImport.update({
  id: '/products/packages',
  path: '/products/packages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsServicesRoute = AdminProductsServicesRouteImport.update({
  id: '/products/services',
  path: '/products/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsBookingsRoute = AdminReportsBookingsRouteImport.update({
  id: '/reports/bookings',
  path: '/reports/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRevenueRoute = AdminReportsRevenueRouteImport.update({
  id: '/reports/revenue',
  path: '/reports/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsBookingRoute = AdminSettingsBookingRouteImport.update({
  id: '/settings/booking',
  path: '/settings/booking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsContactRoute = AdminSettingsContactRouteImport.update({
  id: '/settings/contact',
  path: '/settings/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsGeneralRoute = AdminSettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsPaymentRoute = AdminSettingsPaymentRouteImport.update({
  id: '/settings/payment',
  path: '/settings/payment',
  getParentRoute: () => AdminRoute,
} as any)
const BookHotelIndexRoute = BookHotelIndexRouteImport.update({
  id: '/book/hotel/',
  path: '/book/hotel/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookHotelConfirmationRoute = BookHotelConfirmationRouteImport.update({
  id: '/book/hotel/confirmation',
  path: '/book/hotel/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTourPackageIndexRoute = BookTourPackageIndexRouteImport.update({
  id: '/book/tour-package/',
  path: '/book/tour-package/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTourPackageConfirmationRoute =
  BookTourPackageConfirmationRouteImport.update({
    id: '/book/tour-package/confirmation',
    path: '/book/tour-package/confirmation',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardIndexRoute = CustomerDashboardIndexRouteImport.update({
  id: '/customer/dashboard/',
  path: '/customer/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardCancellationsRoute =
  CustomerDashboardCancellationsRouteImport.update({
    id: '/customer/dashboard/cancellations',
    path: '/customer/dashboard/cancellations',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardConfirmationsRoute =
  CustomerDashboardConfirmationsRouteImport.update({
    id: '/customer/dashboard/confirmations',
    path: '/customer/dashboard/confirmations',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardInvoicesRoute =
  CustomerDashboardInvoicesRouteImport.update({
    id: '/customer/dashboard/invoices',
    path: '/customer/dashboard/invoices',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardPaymentsRoute =
  CustomerDashboardPaymentsRouteImport.update({
    id: '/customer/dashboard/payments',
    path: '/customer/dashboard/payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardProfileRoute =
  CustomerDashboardProfileRouteImport.update({
    id: '/customer/dashboard/profile',
    path: '/customer/dashboard/profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardStatusRoute = CustomerDashboardStatusRouteImport.update({
  id: '/customer/dashboard/status',
  path: '/customer/dashboard/status',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardSupportRoute =
  CustomerDashboardSupportRouteImport.update({
    id: '/customer/dashboard/support',
    path: '/customer/dashboard/support',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardTravellersRoute =
  CustomerDashboardTravellersRouteImport.update({
    id: '/customer/dashboard/travellers',
    path: '/customer/dashboard/travellers',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelsDestinationSlugIndexRoute =
  HotelsDestinationSlugIndexRouteImport.update({
    id: '/hotels/$destinationSlug/',
    path: '/hotels/$destinationSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardBookingsIndexRoute =
  CustomerDashboardBookingsIndexRouteImport.update({
    id: '/customer/dashboard/bookings/',
    path: '/customer/dashboard/bookings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardBookingsHotelRoute =
  CustomerDashboardBookingsHotelRouteImport.update({
    id: '/customer/dashboard/bookings/hotel',
    path: '/customer/dashboard/bookings/hotel',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardBookingsTourRoute =
  CustomerDashboardBookingsTourRouteImport.update({
    id: '/customer/dashboard/bookings/tour',
    path: '/customer/dashboard/bookings/tour',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomerDashboardBookingsVehicleRoute =
  CustomerDashboardBookingsVehicleRouteImport.update({
    id: '/customer/dashboard/bookings/vehicle',
    path: '/customer/dashboard/bookings/vehicle',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelsDestinationSlugHotelSlugIndexRoute =
  HotelsDestinationSlugHotelSlugIndexRouteImport.update({
    id: '/hotels/$destinationSlug/$hotelSlug/',
    path: '/hotels/$destinationSlug/$hotelSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HotelsDestinationSlugHotelSlugRoomSlugRoute =
  HotelsDestinationSlugHotelSlugRoomSlugRouteImport.update({
    id: '/hotels/$destinationSlug/$hotelSlug/$roomSlug',
    path: '/hotels/$destinationSlug/$hotelSlug/$roomSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking-status': typeof BookingStatusRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/custom-tour': typeof CustomTourRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/qr-payment': typeof QrPaymentRoute
  '/rate-cards': typeof RateCardsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/booking-confirmation/$bookingNumber': typeof BookingConfirmationBookingNumberRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/login': typeof CustomerLoginRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/fleet/$slug': typeof FleetSlugRoute
  '/hotels/search': typeof HotelsSearchRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tour-packages/$slug': typeof TourPackagesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/fleet/': typeof FleetIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tour-packages/': typeof TourPackagesIndexRoute
  '/admin/administration/logs': typeof AdminAdministrationLogsRoute
  '/admin/administration/users': typeof AdminAdministrationUsersRoute
  '/admin/cms/hero': typeof AdminCmsHeroRoute
  '/admin/cms/testimonials': typeof AdminCmsTestimonialsRoute
  '/admin/content/faqs': typeof AdminContentFaqsRoute
  '/admin/content/footer': typeof AdminContentFooterRoute
  '/admin/content/gallery': typeof AdminContentGalleryRoute
  '/admin/content/hero': typeof AdminContentHeroRoute
  '/admin/content/homepage': typeof AdminContentHomepageRoute
  '/admin/content/navigation': typeof AdminContentNavigationRoute
  '/admin/content/testimonials': typeof AdminContentTestimonialsRoute
  '/admin/operations/bookings': typeof AdminOperationsBookingsRoute
  '/admin/operations/customers': typeof AdminOperationsCustomersRoute
  '/admin/operations/drivers': typeof AdminOperationsDriversRoute
  '/admin/operations/enquiries': typeof AdminOperationsEnquiriesRoute
  '/admin/operations/payments': typeof AdminOperationsPaymentsRoute
  '/admin/operations/routes': typeof AdminOperationsRoutesRoute
  '/admin/operations/vehicles': typeof AdminOperationsVehiclesRoute
  '/admin/products/destinations': typeof AdminProductsDestinationsRoute
  '/admin/products/fleet': typeof AdminProductsFleetRoute
  '/admin/products/hotels': typeof AdminProductsHotelsRoute
  '/admin/products/packages': typeof AdminProductsPackagesRoute
  '/admin/products/services': typeof AdminProductsServicesRoute
  '/admin/reports/bookings': typeof AdminReportsBookingsRoute
  '/admin/reports/revenue': typeof AdminReportsRevenueRoute
  '/admin/settings/booking': typeof AdminSettingsBookingRoute
  '/admin/settings/contact': typeof AdminSettingsContactRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/payment': typeof AdminSettingsPaymentRoute
  '/book/hotel/confirmation': typeof BookHotelConfirmationRoute
  '/book/tour-package/confirmation': typeof BookTourPackageConfirmationRoute
  '/customer/dashboard/cancellations': typeof CustomerDashboardCancellationsRoute
  '/customer/dashboard/confirmations': typeof CustomerDashboardConfirmationsRoute
  '/customer/dashboard/invoices': typeof CustomerDashboardInvoicesRoute
  '/customer/dashboard/payments': typeof CustomerDashboardPaymentsRoute
  '/customer/dashboard/profile': typeof CustomerDashboardProfileRoute
  '/customer/dashboard/status': typeof CustomerDashboardStatusRoute
  '/customer/dashboard/support': typeof CustomerDashboardSupportRoute
  '/customer/dashboard/travellers': typeof CustomerDashboardTravellersRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/book/hotel/': typeof BookHotelIndexRoute
  '/book/tour-package/': typeof BookTourPackageIndexRoute
  '/customer/dashboard/': typeof CustomerDashboardIndexRoute
  '/hotels/$destinationSlug/': typeof HotelsDestinationSlugIndexRoute
  '/customer/dashboard/bookings/hotel': typeof CustomerDashboardBookingsHotelRoute
  '/customer/dashboard/bookings/tour': typeof CustomerDashboardBookingsTourRoute
  '/customer/dashboard/bookings/vehicle': typeof CustomerDashboardBookingsVehicleRoute
  '/hotels/$destinationSlug/$hotelSlug/$roomSlug': typeof HotelsDestinationSlugHotelSlugRoomSlugRoute
  '/customer/dashboard/bookings/': typeof CustomerDashboardBookingsIndexRoute
  '/hotels/$destinationSlug/$hotelSlug/': typeof HotelsDestinationSlugHotelSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/booking-status': typeof BookingStatusRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/custom-tour': typeof CustomTourRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/qr-payment': typeof QrPaymentRoute
  '/rate-cards': typeof RateCardsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/login': typeof AdminLoginRoute
  '/booking-confirmation/$bookingNumber': typeof BookingConfirmationBookingNumberRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/login': typeof CustomerLoginRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/fleet/$slug': typeof FleetSlugRoute
  '/hotels/search': typeof HotelsSearchRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tour-packages/$slug': typeof TourPackagesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/fleet': typeof FleetIndexRoute
  '/hotels': typeof HotelsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/tour-packages': typeof TourPackagesIndexRoute
  '/admin/administration/logs': typeof AdminAdministrationLogsRoute
  '/admin/administration/users': typeof AdminAdministrationUsersRoute
  '/admin/cms/hero': typeof AdminCmsHeroRoute
  '/admin/cms/testimonials': typeof AdminCmsTestimonialsRoute
  '/admin/content/faqs': typeof AdminContentFaqsRoute
  '/admin/content/footer': typeof AdminContentFooterRoute
  '/admin/content/gallery': typeof AdminContentGalleryRoute
  '/admin/content/hero': typeof AdminContentHeroRoute
  '/admin/content/homepage': typeof AdminContentHomepageRoute
  '/admin/content/navigation': typeof AdminContentNavigationRoute
  '/admin/content/testimonials': typeof AdminContentTestimonialsRoute
  '/admin/operations/bookings': typeof AdminOperationsBookingsRoute
  '/admin/operations/customers': typeof AdminOperationsCustomersRoute
  '/admin/operations/drivers': typeof AdminOperationsDriversRoute
  '/admin/operations/enquiries': typeof AdminOperationsEnquiriesRoute
  '/admin/operations/payments': typeof AdminOperationsPaymentsRoute
  '/admin/operations/routes': typeof AdminOperationsRoutesRoute
  '/admin/operations/vehicles': typeof AdminOperationsVehiclesRoute
  '/admin/products/destinations': typeof AdminProductsDestinationsRoute
  '/admin/products/fleet': typeof AdminProductsFleetRoute
  '/admin/products/hotels': typeof AdminProductsHotelsRoute
  '/admin/products/packages': typeof AdminProductsPackagesRoute
  '/admin/products/services': typeof AdminProductsServicesRoute
  '/admin/reports/bookings': typeof AdminReportsBookingsRoute
  '/admin/reports/revenue': typeof AdminReportsRevenueRoute
  '/admin/settings/booking': typeof AdminSettingsBookingRoute
  '/admin/settings/contact': typeof AdminSettingsContactRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/payment': typeof AdminSettingsPaymentRoute
  '/book/hotel/confirmation': typeof BookHotelConfirmationRoute
  '/book/tour-package/confirmation': typeof BookTourPackageConfirmationRoute
  '/customer/dashboard/cancellations': typeof CustomerDashboardCancellationsRoute
  '/customer/dashboard/confirmations': typeof CustomerDashboardConfirmationsRoute
  '/customer/dashboard/invoices': typeof CustomerDashboardInvoicesRoute
  '/customer/dashboard/payments': typeof CustomerDashboardPaymentsRoute
  '/customer/dashboard/profile': typeof CustomerDashboardProfileRoute
  '/customer/dashboard/status': typeof CustomerDashboardStatusRoute
  '/customer/dashboard/support': typeof CustomerDashboardSupportRoute
  '/customer/dashboard/travellers': typeof CustomerDashboardTravellersRoute
  '/admin/cms': typeof AdminCmsIndexRoute
  '/book/hotel': typeof BookHotelIndexRoute
  '/book/tour-package': typeof BookTourPackageIndexRoute
  '/customer/dashboard': typeof CustomerDashboardIndexRoute
  '/hotels/$destinationSlug': typeof HotelsDestinationSlugIndexRoute
  '/customer/dashboard/bookings/hotel': typeof CustomerDashboardBookingsHotelRoute
  '/customer/dashboard/bookings/tour': typeof CustomerDashboardBookingsTourRoute
  '/customer/dashboard/bookings/vehicle': typeof CustomerDashboardBookingsVehicleRoute
  '/hotels/$destinationSlug/$hotelSlug/$roomSlug': typeof HotelsDestinationSlugHotelSlugRoomSlugRoute
  '/customer/dashboard/bookings': typeof CustomerDashboardBookingsIndexRoute
  '/hotels/$destinationSlug/$hotelSlug': typeof HotelsDestinationSlugHotelSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking-status': typeof BookingStatusRoute
  '/contact': typeof ContactRoute
  '/contact-us': typeof ContactUsRoute
  '/custom-tour': typeof CustomTourRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/packages': typeof PackagesRoute
  '/qr-payment': typeof QrPaymentRoute
  '/rate-cards': typeof RateCardsRoute
  '/testimonials': typeof TestimonialsRoute
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/booking-confirmation/$bookingNumber': typeof BookingConfirmationBookingNumberRoute
  '/customer/account': typeof CustomerAccountRoute
  '/customer/login': typeof CustomerLoginRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/fleet/$slug': typeof FleetSlugRoute
  '/hotels/search': typeof HotelsSearchRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tour-packages/$slug': typeof TourPackagesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/fleet/': typeof FleetIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tour-packages/': typeof TourPackagesIndexRoute
  '/admin/administration/logs': typeof AdminAdministrationLogsRoute
  '/admin/administration/users': typeof AdminAdministrationUsersRoute
  '/admin/cms/hero': typeof AdminCmsHeroRoute
  '/admin/cms/testimonials': typeof AdminCmsTestimonialsRoute
  '/admin/content/faqs': typeof AdminContentFaqsRoute
  '/admin/content/footer': typeof AdminContentFooterRoute
  '/admin/content/gallery': typeof AdminContentGalleryRoute
  '/admin/content/hero': typeof AdminContentHeroRoute
  '/admin/content/homepage': typeof AdminContentHomepageRoute
  '/admin/content/navigation': typeof AdminContentNavigationRoute
  '/admin/content/testimonials': typeof AdminContentTestimonialsRoute
  '/admin/operations/bookings': typeof AdminOperationsBookingsRoute
  '/admin/operations/customers': typeof AdminOperationsCustomersRoute
  '/admin/operations/drivers': typeof AdminOperationsDriversRoute
  '/admin/operations/enquiries': typeof AdminOperationsEnquiriesRoute
  '/admin/operations/payments': typeof AdminOperationsPaymentsRoute
  '/admin/operations/routes': typeof AdminOperationsRoutesRoute
  '/admin/operations/vehicles': typeof AdminOperationsVehiclesRoute
  '/admin/products/destinations': typeof AdminProductsDestinationsRoute
  '/admin/products/fleet': typeof AdminProductsFleetRoute
  '/admin/products/hotels': typeof AdminProductsHotelsRoute
  '/admin/products/packages': typeof AdminProductsPackagesRoute
  '/admin/products/services': typeof AdminProductsServicesRoute
  '/admin/reports/bookings': typeof AdminReportsBookingsRoute
  '/admin/reports/revenue': typeof AdminReportsRevenueRoute
  '/admin/settings/booking': typeof AdminSettingsBookingRoute
  '/admin/settings/contact': typeof AdminSettingsContactRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/payment': typeof AdminSettingsPaymentRoute
  '/book/hotel/confirmation': typeof BookHotelConfirmationRoute
  '/book/tour-package/confirmation': typeof BookTourPackageConfirmationRoute
  '/customer/dashboard/cancellations': typeof CustomerDashboardCancellationsRoute
  '/customer/dashboard/confirmations': typeof CustomerDashboardConfirmationsRoute
  '/customer/dashboard/invoices': typeof CustomerDashboardInvoicesRoute
  '/customer/dashboard/payments': typeof CustomerDashboardPaymentsRoute
  '/customer/dashboard/profile': typeof CustomerDashboardProfileRoute
  '/customer/dashboard/status': typeof CustomerDashboardStatusRoute
  '/customer/dashboard/support': typeof CustomerDashboardSupportRoute
  '/customer/dashboard/travellers': typeof CustomerDashboardTravellersRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/book/hotel/': typeof BookHotelIndexRoute
  '/book/tour-package/': typeof BookTourPackageIndexRoute
  '/customer/dashboard/': typeof CustomerDashboardIndexRoute
  '/hotels/$destinationSlug/': typeof HotelsDestinationSlugIndexRoute
  '/customer/dashboard/bookings/hotel': typeof CustomerDashboardBookingsHotelRoute
  '/customer/dashboard/bookings/tour': typeof CustomerDashboardBookingsTourRoute
  '/customer/dashboard/bookings/vehicle': typeof CustomerDashboardBookingsVehicleRoute
  '/hotels/$destinationSlug/$hotelSlug/$roomSlug': typeof HotelsDestinationSlugHotelSlugRoomSlugRoute
  '/customer/dashboard/bookings/': typeof CustomerDashboardBookingsIndexRoute
  '/hotels/$destinationSlug/$hotelSlug/': typeof HotelsDestinationSlugHotelSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-us'
    | '/admin'
    | '/booking-status'
    | '/contact'
    | '/contact-us'
    | '/custom-tour'
    | '/faqs'
    | '/gallery'
    | '/packages'
    | '/qr-payment'
    | '/rate-cards'
    | '/testimonials'
    | '/admin/cms'
    | '/admin/login'
    | '/booking-confirmation/$bookingNumber'
    | '/customer/account'
    | '/customer/login'
    | '/destinations/$slug'
    | '/fleet/$slug'
    | '/hotels/search'
    | '/services/$slug'
    | '/tour-packages/$slug'
    | '/admin/'
    | '/destinations/'
    | '/fleet/'
    | '/hotels/'
    | '/services/'
    | '/tour-packages/'
    | '/admin/administration/logs'
    | '/admin/administration/users'
    | '/admin/cms/hero'
    | '/admin/cms/testimonials'
    | '/admin/content/faqs'
    | '/admin/content/footer'
    | '/admin/content/gallery'
    | '/admin/content/hero'
    | '/admin/content/homepage'
    | '/admin/content/navigation'
    | '/admin/content/testimonials'
    | '/admin/operations/bookings'
    | '/admin/operations/customers'
    | '/admin/operations/drivers'
    | '/admin/operations/enquiries'
    | '/admin/operations/payments'
    | '/admin/operations/routes'
    | '/admin/operations/vehicles'
    | '/admin/products/destinations'
    | '/admin/products/fleet'
    | '/admin/products/hotels'
    | '/admin/products/packages'
    | '/admin/products/services'
    | '/admin/reports/bookings'
    | '/admin/reports/revenue'
    | '/admin/settings/booking'
    | '/admin/settings/contact'
    | '/admin/settings/general'
    | '/admin/settings/payment'
    | '/book/hotel/confirmation'
    | '/book/tour-package/confirmation'
    | '/customer/dashboard/cancellations'
    | '/customer/dashboard/confirmations'
    | '/customer/dashboard/invoices'
    | '/customer/dashboard/payments'
    | '/customer/dashboard/profile'
    | '/customer/dashboard/status'
    | '/customer/dashboard/support'
    | '/customer/dashboard/travellers'
    | '/admin/cms/'
    | '/book/hotel/'
    | '/book/tour-package/'
    | '/customer/dashboard/'
    | '/hotels/$destinationSlug/'
    | '/customer/dashboard/bookings/hotel'
    | '/customer/dashboard/bookings/tour'
    | '/customer/dashboard/bookings/vehicle'
    | '/hotels/$destinationSlug/$hotelSlug/$roomSlug'
    | '/customer/dashboard/bookings/'
    | '/hotels/$destinationSlug/$hotelSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-us'
    | '/booking-status'
    | '/contact'
    | '/contact-us'
    | '/custom-tour'
    | '/faqs'
    | '/gallery'
    | '/packages'
    | '/qr-payment'
    | '/rate-cards'
    | '/testimonials'
    | '/admin/login'
    | '/booking-confirmation/$bookingNumber'
    | '/customer/account'
    | '/customer/login'
    | '/destinations/$slug'
    | '/fleet/$slug'
    | '/hotels/search'
    | '/services/$slug'
    | '/tour-packages/$slug'
    | '/admin'
    | '/destinations'
    | '/fleet'
    | '/hotels'
    | '/services'
    | '/tour-packages'
    | '/admin/administration/logs'
    | '/admin/administration/users'
    | '/admin/cms/hero'
    | '/admin/cms/testimonials'
    | '/admin/content/faqs'
    | '/admin/content/footer'
    | '/admin/content/gallery'
    | '/admin/content/hero'
    | '/admin/content/homepage'
    | '/admin/content/navigation'
    | '/admin/content/testimonials'
    | '/admin/operations/bookings'
    | '/admin/operations/customers'
    | '/admin/operations/drivers'
    | '/admin/operations/enquiries'
    | '/admin/operations/payments'
    | '/admin/operations/routes'
    | '/admin/operations/vehicles'
    | '/admin/products/destinations'
    | '/admin/products/fleet'
    | '/admin/products/hotels'
    | '/admin/products/packages'
    | '/admin/products/services'
    | '/admin/reports/bookings'
    | '/admin/reports/revenue'
    | '/admin/settings/booking'
    | '/admin/settings/contact'
    | '/admin/settings/general'
    | '/admin/settings/payment'
    | '/book/hotel/confirmation'
    | '/book/tour-package/confirmation'
    | '/customer/dashboard/cancellations'
    | '/customer/dashboard/confirmations'
    | '/customer/dashboard/invoices'
    | '/customer/dashboard/payments'
    | '/customer/dashboard/profile'
    | '/customer/dashboard/status'
    | '/customer/dashboard/support'
    | '/customer/dashboard/travellers'
    | '/admin/cms'
    | '/book/hotel'
    | '/book/tour-package'
    | '/customer/dashboard'
    | '/hotels/$destinationSlug'
    | '/customer/dashboard/bookings/hotel'
    | '/customer/dashboard/bookings/tour'
    | '/customer/dashboard/bookings/vehicle'
    | '/hotels/$destinationSlug/$hotelSlug/$roomSlug'
    | '/customer/dashboard/bookings'
    | '/hotels/$destinationSlug/$hotelSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-us'
    | '/admin'
    | '/booking-status'
    | '/contact'
    | '/contact-us'
    | '/custom-tour'
    | '/faqs'
    | '/gallery'
    | '/packages'
    | '/qr-payment'
    | '/rate-cards'
    | '/testimonials'
    | '/admin/cms'
    | '/admin/login'
    | '/booking-confirmation/$bookingNumber'
    | '/customer/account'
    | '/customer/login'
    | '/destinations/$slug'
    | '/fleet/$slug'
    | '/hotels/search'
    | '/services/$slug'
    | '/tour-packages/$slug'
    | '/admin/'
    | '/destinations/'
    | '/fleet/'
    | '/hotels/'
    | '/services/'
    | '/tour-packages/'
    | '/admin/administration/logs'
    | '/admin/administration/users'
    | '/admin/cms/hero'
    | '/admin/cms/testimonials'
    | '/admin/content/faqs'
    | '/admin/content/footer'
    | '/admin/content/gallery'
    | '/admin/content/hero'
    | '/admin/content/homepage'
    | '/admin/content/navigation'
    | '/admin/content/testimonials'
    | '/admin/operations/bookings'
    | '/admin/operations/customers'
    | '/admin/operations/drivers'
    | '/admin/operations/enquiries'
    | '/admin/operations/payments'
    | '/admin/operations/routes'
    | '/admin/operations/vehicles'
    | '/admin/products/destinations'
    | '/admin/products/fleet'
    | '/admin/products/hotels'
    | '/admin/products/packages'
    | '/admin/products/services'
    | '/admin/reports/bookings'
    | '/admin/reports/revenue'
    | '/admin/settings/booking'
    | '/admin/settings/contact'
    | '/admin/settings/general'
    | '/admin/settings/payment'
    | '/book/hotel/confirmation'
    | '/book/tour-package/confirmation'
    | '/customer/dashboard/cancellations'
    | '/customer/dashboard/confirmations'
    | '/customer/dashboard/invoices'
    | '/customer/dashboard/payments'
    | '/customer/dashboard/profile'
    | '/customer/dashboard/status'
    | '/customer/dashboard/support'
    | '/customer/dashboard/travellers'
    | '/admin/cms/'
    | '/book/hotel/'
    | '/book/tour-package/'
    | '/customer/dashboard/'
    | '/hotels/$destinationSlug/'
    | '/customer/dashboard/bookings/hotel'
    | '/customer/dashboard/bookings/tour'
    | '/customer/dashboard/bookings/vehicle'
    | '/hotels/$destinationSlug/$hotelSlug/$roomSlug'
    | '/customer/dashboard/bookings/'
    | '/hotels/$destinationSlug/$hotelSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingStatusRoute: typeof BookingStatusRoute
  ContactRoute: typeof ContactRoute
  ContactUsRoute: typeof ContactUsRoute
  CustomTourRoute: typeof CustomTourRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  PackagesRoute: typeof PackagesRoute
  QrPaymentRoute: typeof QrPaymentRoute
  RateCardsRoute: typeof RateCardsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  BookingConfirmationBookingNumberRoute: typeof BookingConfirmationBookingNumberRoute
  CustomerAccountRoute: typeof CustomerAccountRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  FleetSlugRoute: typeof FleetSlugRoute
  HotelsSearchRoute: typeof HotelsSearchRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  TourPackagesSlugRoute: typeof TourPackagesSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  FleetIndexRoute: typeof FleetIndexRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TourPackagesIndexRoute: typeof TourPackagesIndexRoute
  BookHotelConfirmationRoute: typeof BookHotelConfirmationRoute
  BookTourPackageConfirmationRoute: typeof BookTourPackageConfirmationRoute
  CustomerDashboardCancellationsRoute: typeof CustomerDashboardCancellationsRoute
  CustomerDashboardConfirmationsRoute: typeof CustomerDashboardConfirmationsRoute
  CustomerDashboardInvoicesRoute: typeof CustomerDashboardInvoicesRoute
  CustomerDashboardPaymentsRoute: typeof CustomerDashboardPaymentsRoute
  CustomerDashboardProfileRoute: typeof CustomerDashboardProfileRoute
  CustomerDashboardStatusRoute: typeof CustomerDashboardStatusRoute
  CustomerDashboardSupportRoute: typeof CustomerDashboardSupportRoute
  CustomerDashboardTravellersRoute: typeof CustomerDashboardTravellersRoute
  BookHotelIndexRoute: typeof BookHotelIndexRoute
  BookTourPackageIndexRoute: typeof BookTourPackageIndexRoute
  CustomerDashboardIndexRoute: typeof CustomerDashboardIndexRoute
  HotelsDestinationSlugIndexRoute: typeof HotelsDestinationSlugIndexRoute
  CustomerDashboardBookingsHotelRoute: typeof CustomerDashboardBookingsHotelRoute
  CustomerDashboardBookingsTourRoute: typeof CustomerDashboardBookingsTourRoute
  CustomerDashboardBookingsVehicleRoute: typeof CustomerDashboardBookingsVehicleRoute
  HotelsDestinationSlugHotelSlugRoomSlugRoute: typeof HotelsDestinationSlugHotelSlugRoomSlugRoute
  CustomerDashboardBookingsIndexRoute: typeof CustomerDashboardBookingsIndexRoute
  HotelsDestinationSlugHotelSlugIndexRoute: typeof HotelsDestinationSlugHotelSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-status': {
      id: '/booking-status'
      path: '/booking-status'
      fullPath: '/booking-status'
      preLoaderRoute: typeof BookingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-tour': {
      id: '/custom-tour'
      path: '/custom-tour'
      fullPath: '/custom-tour'
      preLoaderRoute: typeof CustomTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-payment': {
      id: '/qr-payment'
      path: '/qr-payment'
      fullPath: '/qr-payment'
      preLoaderRoute: typeof QrPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-cards': {
      id: '/rate-cards'
      path: '/rate-cards'
      fullPath: '/rate-cards'
      preLoaderRoute: typeof RateCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/booking-confirmation/$bookingNumber': {
      id: '/booking-confirmation/$bookingNumber'
      path: '/booking-confirmation/$bookingNumber'
      fullPath: '/booking-confirmation/$bookingNumber'
      preLoaderRoute: typeof BookingConfirmationBookingNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/account': {
      id: '/customer/account'
      path: '/customer/account'
      fullPath: '/customer/account'
      preLoaderRoute: typeof CustomerAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/customer/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/': {
      id: '/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof FleetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/$slug': {
      id: '/fleet/$slug'
      path: '/fleet/$slug'
      fullPath: '/fleet/$slug'
      preLoaderRoute: typeof FleetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/search': {
      id: '/hotels/search'
      path: '/hotels/search'
      fullPath: '/hotels/search'
      preLoaderRoute: typeof HotelsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-packages/': {
      id: '/tour-packages/'
      path: '/tour-packages'
      fullPath: '/tour-packages/'
      preLoaderRoute: typeof TourPackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-packages/$slug': {
      id: '/tour-packages/$slug'
      path: '/tour-packages/$slug'
      fullPath: '/tour-packages/$slug'
      preLoaderRoute: typeof TourPackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/administration/logs': {
      id: '/admin/administration/logs'
      path: '/administration/logs'
      fullPath: '/admin/administration/logs'
      preLoaderRoute: typeof AdminAdministrationLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administration/users': {
      id: '/admin/administration/users'
      path: '/administration/users'
      fullPath: '/admin/administration/users'
      preLoaderRoute: typeof AdminAdministrationUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/': {
      id: '/admin/cms/'
      path: '/'
      fullPath: '/admin/cms/'
      preLoaderRoute: typeof AdminCmsIndexRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/hero': {
      id: '/admin/cms/hero'
      path: '/hero'
      fullPath: '/admin/cms/hero'
      preLoaderRoute: typeof AdminCmsHeroRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/testimonials': {
      id: '/admin/cms/testimonials'
      path: '/testimonials'
      fullPath: '/admin/cms/testimonials'
      preLoaderRoute: typeof AdminCmsTestimonialsRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/content/faqs': {
      id: '/admin/content/faqs'
      path: '/content/faqs'
      fullPath: '/admin/content/faqs'
      preLoaderRoute: typeof AdminContentFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/footer': {
      id: '/admin/content/footer'
      path: '/content/footer'
      fullPath: '/admin/content/footer'
      preLoaderRoute: typeof AdminContentFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/gallery': {
      id: '/admin/content/gallery'
      path: '/content/gallery'
      fullPath: '/admin/content/gallery'
      preLoaderRoute: typeof AdminContentGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/hero': {
      id: '/admin/content/hero'
      path: '/content/hero'
      fullPath: '/admin/content/hero'
      preLoaderRoute: typeof AdminContentHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/homepage': {
      id: '/admin/content/homepage'
      path: '/content/homepage'
      fullPath: '/admin/content/homepage'
      preLoaderRoute: typeof AdminContentHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/navigation': {
      id: '/admin/content/navigation'
      path: '/content/navigation'
      fullPath: '/admin/content/navigation'
      preLoaderRoute: typeof AdminContentNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/testimonials': {
      id: '/admin/content/testimonials'
      path: '/content/testimonials'
      fullPath: '/admin/content/testimonials'
      preLoaderRoute: typeof AdminContentTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations/bookings': {
      id: '/admin/operations/bookings'
      path: '/operations/bookings'
      fullPath: '/admin/operations/bookings'
      preLoaderRoute: typeof AdminOperationsBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations/customers': {
      id: '/admin/operations/customers'
      path: '/operations/customers'
      fullPath: '/admin/operations/customers'
      preLoaderRoute: typeof AdminOperationsCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations/drivers': {
      id: '/admin/operations/drivers'
      path: '/operations/drivers'
      fullPath: '/admin/operations/drivers'
      preLoaderRoute: typeof AdminOperationsDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations/enquiries': {
      id: '/admin/operations/enquiries'
      path: '/operations/enquiries'
      fullPath: '/admin/operations/enquiries'
      preLoaderRoute: typeof AdminOperationsEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations/payments': {
      id: '/admin/operations/payments'
      path: '/operations/payments'
      fullPath: '/admin/operations/payments'
      preLoaderRoute: typeof AdminOperationsPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations/routes': {
      id: '/admin/operations/routes'
      path: '/operations/routes'
      fullPath: '/admin/operations/routes'
      preLoaderRoute: typeof AdminOperationsRoutesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/operations/vehicles': {
      id: '/admin/operations/vehicles'
      path: '/operations/vehicles'
      fullPath: '/admin/operations/vehicles'
      preLoaderRoute: typeof AdminOperationsVehiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/destinations': {
      id: '/admin/products/destinations'
      path: '/products/destinations'
      fullPath: '/admin/products/destinations'
      preLoaderRoute: typeof AdminProductsDestinationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/fleet': {
      id: '/admin/products/fleet'
      path: '/products/fleet'
      fullPath: '/admin/products/fleet'
      preLoaderRoute: typeof AdminProductsFleetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/hotels': {
      id: '/admin/products/hotels'
      path: '/products/hotels'
      fullPath: '/admin/products/hotels'
      preLoaderRoute: typeof AdminProductsHotelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/packages': {
      id: '/admin/products/packages'
      path: '/products/packages'
      fullPath: '/admin/products/packages'
      preLoaderRoute: typeof AdminProductsPackagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/services': {
      id: '/admin/products/services'
      path: '/products/services'
      fullPath: '/admin/products/services'
      preLoaderRoute: typeof AdminProductsServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/bookings': {
      id: '/admin/reports/bookings'
      path: '/reports/bookings'
      fullPath: '/admin/reports/bookings'
      preLoaderRoute: typeof AdminReportsBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/revenue': {
      id: '/admin/reports/revenue'
      path: '/reports/revenue'
      fullPath: '/admin/reports/revenue'
      preLoaderRoute: typeof AdminReportsRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/booking': {
      id: '/admin/settings/booking'
      path: '/settings/booking'
      fullPath: '/admin/settings/booking'
      preLoaderRoute: typeof AdminSettingsBookingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/contact': {
      id: '/admin/settings/contact'
      path: '/settings/contact'
      fullPath: '/admin/settings/contact'
      preLoaderRoute: typeof AdminSettingsContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/general': {
      id: '/admin/settings/general'
      path: '/settings/general'
      fullPath: '/admin/settings/general'
      preLoaderRoute: typeof AdminSettingsGeneralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/payment': {
      id: '/admin/settings/payment'
      path: '/settings/payment'
      fullPath: '/admin/settings/payment'
      preLoaderRoute: typeof AdminSettingsPaymentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/book/hotel/': {
      id: '/book/hotel/'
      path: '/book/hotel'
      fullPath: '/book/hotel/'
      preLoaderRoute: typeof BookHotelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/hotel/confirmation': {
      id: '/book/hotel/confirmation'
      path: '/book/hotel/confirmation'
      fullPath: '/book/hotel/confirmation'
      preLoaderRoute: typeof BookHotelConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/tour-package/': {
      id: '/book/tour-package/'
      path: '/book/tour-package'
      fullPath: '/book/tour-package/'
      preLoaderRoute: typeof BookTourPackageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/tour-package/confirmation': {
      id: '/book/tour-package/confirmation'
      path: '/book/tour-package/confirmation'
      fullPath: '/book/tour-package/confirmation'
      preLoaderRoute: typeof BookTourPackageConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/': {
      id: '/customer/dashboard/'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard/'
      preLoaderRoute: typeof CustomerDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/cancellations': {
      id: '/customer/dashboard/cancellations'
      path: '/customer/dashboard/cancellations'
      fullPath: '/customer/dashboard/cancellations'
      preLoaderRoute: typeof CustomerDashboardCancellationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/confirmations': {
      id: '/customer/dashboard/confirmations'
      path: '/customer/dashboard/confirmations'
      fullPath: '/customer/dashboard/confirmations'
      preLoaderRoute: typeof CustomerDashboardConfirmationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/invoices': {
      id: '/customer/dashboard/invoices'
      path: '/customer/dashboard/invoices'
      fullPath: '/customer/dashboard/invoices'
      preLoaderRoute: typeof CustomerDashboardInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/payments': {
      id: '/customer/dashboard/payments'
      path: '/customer/dashboard/payments'
      fullPath: '/customer/dashboard/payments'
      preLoaderRoute: typeof CustomerDashboardPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/profile': {
      id: '/customer/dashboard/profile'
      path: '/customer/dashboard/profile'
      fullPath: '/customer/dashboard/profile'
      preLoaderRoute: typeof CustomerDashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/status': {
      id: '/customer/dashboard/status'
      path: '/customer/dashboard/status'
      fullPath: '/customer/dashboard/status'
      preLoaderRoute: typeof CustomerDashboardStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/support': {
      id: '/customer/dashboard/support'
      path: '/customer/dashboard/support'
      fullPath: '/customer/dashboard/support'
      preLoaderRoute: typeof CustomerDashboardSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/travellers': {
      id: '/customer/dashboard/travellers'
      path: '/customer/dashboard/travellers'
      fullPath: '/customer/dashboard/travellers'
      preLoaderRoute: typeof CustomerDashboardTravellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$destinationSlug/': {
      id: '/hotels/$destinationSlug/'
      path: '/hotels/$destinationSlug'
      fullPath: '/hotels/$destinationSlug/'
      preLoaderRoute: typeof HotelsDestinationSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/bookings/': {
      id: '/customer/dashboard/bookings/'
      path: '/customer/dashboard/bookings'
      fullPath: '/customer/dashboard/bookings/'
      preLoaderRoute: typeof CustomerDashboardBookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/bookings/hotel': {
      id: '/customer/dashboard/bookings/hotel'
      path: '/customer/dashboard/bookings/hotel'
      fullPath: '/customer/dashboard/bookings/hotel'
      preLoaderRoute: typeof CustomerDashboardBookingsHotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/bookings/tour': {
      id: '/customer/dashboard/bookings/tour'
      path: '/customer/dashboard/bookings/tour'
      fullPath: '/customer/dashboard/bookings/tour'
      preLoaderRoute: typeof CustomerDashboardBookingsTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard/bookings/vehicle': {
      id: '/customer/dashboard/bookings/vehicle'
      path: '/customer/dashboard/bookings/vehicle'
      fullPath: '/customer/dashboard/bookings/vehicle'
      preLoaderRoute: typeof CustomerDashboardBookingsVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$destinationSlug/$hotelSlug/': {
      id: '/hotels/$destinationSlug/$hotelSlug/'
      path: '/hotels/$destinationSlug/$hotelSlug'
      fullPath: '/hotels/$destinationSlug/$hotelSlug/'
      preLoaderRoute: typeof HotelsDestinationSlugHotelSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$destinationSlug/$hotelSlug/$roomSlug': {
      id: '/hotels/$destinationSlug/$hotelSlug/$roomSlug'
      path: '/hotels/$destinationSlug/$hotelSlug/$roomSlug'
      fullPath: '/hotels/$destinationSlug/$hotelSlug/$roomSlug'
      preLoaderRoute: typeof HotelsDestinationSlugHotelSlugRoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCmsRouteChildren {
  AdminCmsHeroRoute: typeof AdminCmsHeroRoute
  AdminCmsTestimonialsRoute: typeof AdminCmsTestimonialsRoute
  AdminCmsIndexRoute: typeof AdminCmsIndexRoute
}

const AdminCmsRouteChildren: AdminCmsRouteChildren = {
  AdminCmsHeroRoute: AdminCmsHeroRoute,
  AdminCmsTestimonialsRoute: AdminCmsTestimonialsRoute,
  AdminCmsIndexRoute: AdminCmsIndexRoute,
}

const AdminCmsRouteWithChildren = AdminCmsRoute._addFileChildren(
  AdminCmsRouteChildren,
)

interface AdminRouteChildren {
  AdminCmsRoute: typeof AdminCmsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAdministrationLogsRoute: typeof AdminAdministrationLogsRoute
  AdminAdministrationUsersRoute: typeof AdminAdministrationUsersRoute
  AdminContentFaqsRoute: typeof AdminContentFaqsRoute
  AdminContentFooterRoute: typeof AdminContentFooterRoute
  AdminContentGalleryRoute: typeof AdminContentGalleryRoute
  AdminContentHeroRoute: typeof AdminContentHeroRoute
  AdminContentHomepageRoute: typeof AdminContentHomepageRoute
  AdminContentNavigationRoute: typeof AdminContentNavigationRoute
  AdminContentTestimonialsRoute: typeof AdminContentTestimonialsRoute
  AdminOperationsBookingsRoute: typeof AdminOperationsBookingsRoute
  AdminOperationsCustomersRoute: typeof AdminOperationsCustomersRoute
  AdminOperationsDriversRoute: typeof AdminOperationsDriversRoute
  AdminOperationsEnquiriesRoute: typeof AdminOperationsEnquiriesRoute
  AdminOperationsPaymentsRoute: typeof AdminOperationsPaymentsRoute
  AdminOperationsRoutesRoute: typeof AdminOperationsRoutesRoute
  AdminOperationsVehiclesRoute: typeof AdminOperationsVehiclesRoute
  AdminProductsDestinationsRoute: typeof AdminProductsDestinationsRoute
  AdminProductsFleetRoute: typeof AdminProductsFleetRoute
  AdminProductsHotelsRoute: typeof AdminProductsHotelsRoute
  AdminProductsPackagesRoute: typeof AdminProductsPackagesRoute
  AdminProductsServicesRoute: typeof AdminProductsServicesRoute
  AdminReportsBookingsRoute: typeof AdminReportsBookingsRoute
  AdminReportsRevenueRoute: typeof AdminReportsRevenueRoute
  AdminSettingsBookingRoute: typeof AdminSettingsBookingRoute
  AdminSettingsContactRoute: typeof AdminSettingsContactRoute
  AdminSettingsGeneralRoute: typeof AdminSettingsGeneralRoute
  AdminSettingsPaymentRoute: typeof AdminSettingsPaymentRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCmsRoute: AdminCmsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAdministrationLogsRoute: AdminAdministrationLogsRoute,
  AdminAdministrationUsersRoute: AdminAdministrationUsersRoute,
  AdminContentFaqsRoute: AdminContentFaqsRoute,
  AdminContentFooterRoute: AdminContentFooterRoute,
  AdminContentGalleryRoute: AdminContentGalleryRoute,
  AdminContentHeroRoute: AdminContentHeroRoute,
  AdminContentHomepageRoute: AdminContentHomepageRoute,
  AdminContentNavigationRoute: AdminContentNavigationRoute,
  AdminContentTestimonialsRoute: AdminContentTestimonialsRoute,
  AdminOperationsBookingsRoute: AdminOperationsBookingsRoute,
  AdminOperationsCustomersRoute: AdminOperationsCustomersRoute,
  AdminOperationsDriversRoute: AdminOperationsDriversRoute,
  AdminOperationsEnquiriesRoute: AdminOperationsEnquiriesRoute,
  AdminOperationsPaymentsRoute: AdminOperationsPaymentsRoute,
  AdminOperationsRoutesRoute: AdminOperationsRoutesRoute,
  AdminOperationsVehiclesRoute: AdminOperationsVehiclesRoute,
  AdminProductsDestinationsRoute: AdminProductsDestinationsRoute,
  AdminProductsFleetRoute: AdminProductsFleetRoute,
  AdminProductsHotelsRoute: AdminProductsHotelsRoute,
  AdminProductsPackagesRoute: AdminProductsPackagesRoute,
  AdminProductsServicesRoute: AdminProductsServicesRoute,
  AdminReportsBookingsRoute: AdminReportsBookingsRoute,
  AdminReportsRevenueRoute: AdminReportsRevenueRoute,
  AdminSettingsBookingRoute: AdminSettingsBookingRoute,
  AdminSettingsContactRoute: AdminSettingsContactRoute,
  AdminSettingsGeneralRoute: AdminSettingsGeneralRoute,
  AdminSettingsPaymentRoute: AdminSettingsPaymentRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingStatusRoute: BookingStatusRoute,
  ContactRoute: ContactRoute,
  ContactUsRoute: ContactUsRoute,
  CustomTourRoute: CustomTourRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  PackagesRoute: PackagesRoute,
  QrPaymentRoute: QrPaymentRoute,
  RateCardsRoute: RateCardsRoute,
  TestimonialsRoute: TestimonialsRoute,
  BookingConfirmationBookingNumberRoute: BookingConfirmationBookingNumberRoute,
  CustomerAccountRoute: CustomerAccountRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  FleetSlugRoute: FleetSlugRoute,
  HotelsSearchRoute: HotelsSearchRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  TourPackagesSlugRoute: TourPackagesSlugRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  FleetIndexRoute: FleetIndexRoute,
  HotelsIndexRoute: HotelsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TourPackagesIndexRoute: TourPackagesIndexRoute,
  BookHotelConfirmationRoute: BookHotelConfirmationRoute,
  BookTourPackageConfirmationRoute: BookTourPackageConfirmationRoute,
  CustomerDashboardCancellationsRoute: CustomerDashboardCancellationsRoute,
  CustomerDashboardConfirmationsRoute: CustomerDashboardConfirmationsRoute,
  CustomerDashboardInvoicesRoute: CustomerDashboardInvoicesRoute,
  CustomerDashboardPaymentsRoute: CustomerDashboardPaymentsRoute,
  CustomerDashboardProfileRoute: CustomerDashboardProfileRoute,
  CustomerDashboardStatusRoute: CustomerDashboardStatusRoute,
  CustomerDashboardSupportRoute: CustomerDashboardSupportRoute,
  CustomerDashboardTravellersRoute: CustomerDashboardTravellersRoute,
  BookHotelIndexRoute: BookHotelIndexRoute,
  BookTourPackageIndexRoute: BookTourPackageIndexRoute,
  CustomerDashboardIndexRoute: CustomerDashboardIndexRoute,
  HotelsDestinationSlugIndexRoute: HotelsDestinationSlugIndexRoute,
  CustomerDashboardBookingsHotelRoute: CustomerDashboardBookingsHotelRoute,
  CustomerDashboardBookingsTourRoute: CustomerDashboardBookingsTourRoute,
  CustomerDashboardBookingsVehicleRoute: CustomerDashboardBookingsVehicleRoute,
  HotelsDestinationSlugHotelSlugRoomSlugRoute:
    HotelsDestinationSlugHotelSlugRoomSlugRoute,
  CustomerDashboardBookingsIndexRoute: CustomerDashboardBookingsIndexRoute,
  HotelsDestinationSlugHotelSlugIndexRoute:
    HotelsDestinationSlugHotelSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
